plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

bootJar {
    mainClass = 'com.zeydie.dlpsystem.client.ClientLaunch'
    archiveFileName = "${rootProject.rootProject.name}-${rootProject.rootProject.version}.jar"
}

dependencies {
    implementation project(path: ':projects:common')

    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: "${boot}"
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-actuator
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-actuator', version: "${boot}"
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-cache
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-cache', version: "${boot}"
}